TMGR-27: fix ui issues for desktop app
acrossoffwest/task-manager-ui pull request #47
Opened 2023-01-27 21:57 UTC by acrossoffwest

2023-01-28 12:29 UTC, savayer requested changes

2023-01-28 12:29 UTC, savayer commented on package.json
> +		"build:mas": "PYTHON_PATH=/Users/iuriikarpov/.pyenv/shims/python quasar build -m electron --fix -T mas -b builder",
not good )

2023-01-28 12:29 UTC, savayer commented on src/assets/styles/index.scss
> +}
don't rewrite TW styles

2023-01-28 12:29 UTC, savayer commented on src/App.vue
> +				/>
Let's not use quasar components if they don't give us a profit.

2023-01-30 20:18 UTC, acrossoffwest commented on package.json
> +		"build:mas": "PYTHON_PATH=/Users/iuriikarpov/.pyenv/shims/python quasar build -m electron --fix -T mas -b builder",
fix

2023-01-30 20:19 UTC, acrossoffwest commented on src/assets/styles/index.scss
> +}
ok, fix

2023-01-31 14:24 UTC, merged